name: c-linter

on: [push, pull_request]
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: AMReX-Astro/clang-tidy-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_path: :/
